import { z } from "zod";

export const listingSchema = z.object({
  category: z.string().min(1, "Category"),
  purpose: z.string().min(1, "Purpose"),
  type: z.string().min(1, "Property type is required"),
  title: z.string().min(3, "Title (English) is required"),
  size: z.coerce.number().min(1, "Total size is required"),
  sqft: z.coerce.number().optional(),
  bedrooms: z.coerce.number().min(0, "Number of bedrooms is required"),
  bathrooms: z.coerce.number().min(1, "Number of bathrooms is required"),
  parking: z.coerce.number().optional(),
  furnished: z.string().optional(),
  unitNo: z.string().min(1, "Unit Number is required"),
  landNumber: z.string().optional(),
  streetName: z.string().optional(),
  streetDirection: z.string().optional(),
  streetWidth: z.coerce.number().optional().default(0),
  buildYear: z.string().optional(),
  price: z.coerce.number().min(1, "Price is required and must be greater than 0"),
  pricePeriod: z.string().default("Yearly"),
  paymentMethod: z.string().optional(),
  cheques: z.string().optional(),
  serviceCharges: z.string().optional(),
  financialStatus: z.string().optional(),
  description: z.string().min(10, "Description (English) is required"),
  amenities: z.array(z.string()).min(1, "Please select at least one amenity"),
  titleDeed: z.string().optional(),
  landArea: z.coerce.number().optional(),
  builtUpArea: z.coerce.number().optional(),
  layoutType: z.string().optional(),
  projectName: z.string().optional(),
  ownership: z.string().optional(),
  developers: z.string().optional(),
  listingFinished: z.string().optional(),
  currency: z.string().optional(),
  listingAgent: z.string().min(1, "Listing Agent (Portal) is required"),
  listingOwner: z.string().min(1, "Listing Owner is required"),
  landlord: z.string().optional(),
  availabilityStatus: z.string().optional(),
  availableFrom: z.string().optional(),
  licenseType: z.string().optional(),
  permitNumber: z.string().optional(),
  permitIssueDate: z.string().optional(),
  permitExpiryDate: z.string().optional(),
  adIssueDate: z.string().optional(),
  licenseNo: z.string().optional(),
  furnishingType: z.string().optional(),
  projectStatus: z.string().optional(),
  age: z.coerce.number().optional(),
  floorNumber: z.coerce.number().optional(),
  numberOfFloors: z.coerce.number().optional(),
  locationId: z.coerce.number().optional(),
  propqaLocationId: z.coerce.number().optional(),
  propqaLocationName: z.string().optional(),
  hasGarden: z.boolean().default(false),
  hasKitchen: z.boolean().default(false),
  hasParking: z.boolean().default(false),
  minimalRentalPeriod: z.coerce.number().optional(),
  videoUrl: z.string().optional(),
  view360Url: z.string().optional(),
  qrUrl: z.string().optional(),
  pfLocation: z.union([z.string(), z.number()]).optional(),
  city: z.string().optional(),
  community: z.string().optional(),
  subCommunity: z.string().optional(),
  building: z.string().optional(),
  bayutCity: z.string().optional(),
  bayutLocation: z.union([z.string(), z.number()]).optional(),
  bayutCommunity: z.string().optional(),
  bayutSubCommunity: z.string().optional(),
  bayutBuilding: z.string().optional(),
  uaeEmirate: z.string().optional().default("dubai"),
  reference: z.string().optional(),
  agentEmail: z.string().optional(),
  portals: z.object({
    propertyFinder: z.boolean().default(false),
    bayutEnabled: z.boolean().default(false),
    bayutSelection: z.boolean().default(false),
    dubizzleSelection: z.boolean().default(false),
    officeWebsite: z.boolean().default(false),
    primeZamWebsite: z.boolean().default(false),
    propqaEnabled: z.boolean().default(false),
  }).default({
    propertyFinder: false,
    bayutEnabled: false,
    bayutSelection: false,
    dubizzleSelection: false,
    officeWebsite: false,
    primeZamWebsite: false,
    propqaEnabled: false,
  }),
  notes: z.string().optional(),
  titleAr: z.string().optional(),
  descriptionAr: z.string().optional(),
  images: z.array(z.string()).min(1, "At least one photo is required."),
  floorPlanImage: z.string().optional(),
  documents: z.array(z.string()).optional(),
  publishStatus: z.string().optional(),
  custom_values: z.record(z.string(), z.any()).optional(),
  latitude: z.coerce.number().optional(),
  longitude: z.coerce.number().optional(),
  propqa_lat: z.coerce.number().optional(),
  propqa_lng: z.coerce.number().optional(),
});

export type ListingFormValues = z.infer<typeof listingSchema>;
