import { z } from "zod";

export const listingSchema = z.object({
  category: z.string().min(1, "Category is required"),
  purpose: z.string().min(1, "Purpose is required"),
  type: z.string().min(1, "Property type is required"),
  title: z.string().min(3, "Title must be at least 3 characters"),
  size: z.coerce.number().min(1, "Size must be greater than 0"),
  sqft: z.coerce.number().optional(),
  bedrooms: z.coerce.number().min(0, "Bedrooms is required"),
  bathrooms: z.coerce.number().min(0, "Bathrooms is required"),
  parking: z.coerce.number().optional(),
  furnished: z.string().optional(),
  unitNo: z.string().min(1, "Unit No is required"),
  buildYear: z.string().optional(),
  price: z.coerce.number().min(1, "Price must be greater than 0"),
  pricePeriod: z.string().default("Yearly"),
  paymentMethod: z.string().optional(),
  cheques: z.string().optional(),
  serviceCharges: z.string().optional(),
  financialStatus: z.string().optional(),
  description: z.string().optional(),
  amenities: z.array(z.string()).optional(),
  titleDeed: z.string().optional(),
  landArea: z.coerce.number().optional(),
  builtUpArea: z.coerce.number().optional(),
  layoutType: z.string().optional(),
  projectName: z.string().optional(),
  ownership: z.string().optional(),
  developers: z.string().optional(),
  listingFinished: z.string().optional(),
  currency: z.string().default("AED"),
  listingAgent: z.string().min(1, "Listing agent is required"),
  listingOwner: z.string().optional(),
  landlord: z.string().optional(),
  availabilityStatus: z.string().default("Available"),
  availableFrom: z.string().optional(),
  licenseType: z.string().default("Rera"),
  permitNumber: z.string().optional(),
  permitIssueDate: z.string().optional(),
  permitExpiryDate: z.string().optional(),
  videoUrl: z.string().optional(),
  view360Url: z.string().optional(),
  city: z.string().optional(),
  community: z.string().optional(),
  subCommunity: z.string().optional(),
  building: z.string().optional(),
  bayutCity: z.string().optional(),
  bayutCommunity: z.string().optional(),
  bayutSubCommunity: z.string().optional(),
  bayutBuilding: z.string().optional(),
  portalPF: z.boolean().optional(),
  portalBayut: z.boolean().optional(),
  portalWebsite: z.boolean().optional(),
  notes: z.string().optional(),
  titleAr: z.string().optional(),
  descriptionAr: z.string().optional(),
  images: z.array(z.string()).optional(),
  documents: z.array(z.string()).optional(),
  publishStatus: z.string().optional(),
});

export type ListingFormValues = z.infer<typeof listingSchema>;
